insert into arrangements (id, name, description, deck_id) values (1, 'Tarot de Marseilles', 'Placeholder: The earliest Italian Tarot decks were unnumbered, but as early as 1490 card makers in Ferrara, Italy, began to place Roman numerals on the trumps, fixing them into a specific sequence. This practice was carried on by the early French card makers. It is uncertain which of the Italian trump sequences was adopted in what came to be known as the Tarot of Marseilles, but it is speculated that it may have been the ordering used by the Tarot card makers of Milan.', 1)
insert into arrangements (id, name, description, deck_id) values (2, 'Elphias Levi', 'Placeholder: When Éliphas Lévi brought forth the second volume of his two-part Dogme et Rituel de la Haute Magie, he applied the sequence of the Tarot de Marseilles trumps to the Hebrew alphabet in its traditional order, but he placed the Fool just before the final numbered trump, on the second-last Hebrew letter. Either he did not understand Court de Gébelin’s intention to invert the sequence of trumps, or as seems more likely, he chose to ignore it, or was under oath not to reveal it. He was convinced that the posture of the upper body of the Juggler defined the shape of the first Hebrew letter, Aleph, writing “His body and arms constitute the letter Aleph.” This cannot be denied, but since few, if any, of the other figures on the cards resemble their Hebrew letters, its significance is questionable.
Levi makes no open mention of Sepher Yetzirah attributions.', 1)
insert into arrangements (id, name, description, deck_id) values (3, 'Golden Dawn', 'Placeholder: Included in the esocteric teachings decyphered in the foundational cypher manuscripts of the Golden Dawn, was an authoritative determination that the Fool be placed as the first of the Tarot trumps, before the Juggler, (which in the Golden Dawn Tarot was called the Magician). This advanced all the other Trump associations by one letter, (ex, the Magician now being attributed to Beth, instead of Aleph), which puts the imagery of cards into near perfect alignment with their various zodiacal and elemental attributions as given in the Sepher Yetzirah, save for one more exception to the sequence.', 2)
insert into arrangements (id, name, description, deck_id) values (4, 'Aleister Crowley', 'Truncated Placeholder: Crowley changed the sign attributions of the paths with his Emperor / Star swap specifically to make my database relationships more complicated', 3)
insert into arrangements (id, name, description, deck_id) values (5, 'Frater Achad', 'Placeholder: Tarot for bats', 3)

insert into decks (id, name, description) values (1, 'Tarot de Marseilles', 'Placeholder: The earliest Italian Tarot decks were unnumbered, but as early as 1490 card makers in Ferrara, Italy, began to place Roman numerals on the trumps, fixing them into a specific sequence. This practice was carried on by the early French card makers. It is uncertain which of the Italian trump sequences was adopted in what came to be known as the Tarot of Marseilles, but it is speculated that it may have been the ordering used by the Tarot card makers of Milan.')
insert into decks (id, name, description) values (2, 'Rider-Waite', 'Placeholder: It\'s the one you all know')
insert into decks (id, name, description) values (3, 'Book of Thoth', 'Placeholder: Eternal thanks to Frieda Harris for this artwork, and for bulling Crowley into doing a deck in the first place.')

insert into paths (id, name, utterance, english_name, number) values (1, 'כֶּתֶר', 'Kether (Keṯer)', 'Crown', 1)
insert into paths (id, name, utterance, english_name, number) values (2, 'חָכְמָה', 'Chokmah (ḥoḵmā)', 'Wisdom', 2)
insert into paths (id, name, utterance, english_name, number) values (3, 'בִּינָה', 'Binah (Bīnā)', 'Understanding', 3)
insert into paths (id, name, utterance, english_name, number) values (4, 'חֶסֶד', 'Chesed (Ḥeseḏ)', 'Mercy', 4)
insert into paths (id, name, utterance, english_name, number) values (5, 'גְּבוּרָה', 'Geburah (Gəvūrā)', 'Strength', 5)
insert into paths (id, name, utterance, english_name, number) values (6, 'תִּפְאֶרֶת', 'Tiphereth (Tip̄ʾereṯ)', 'Beauty', 6)
insert into paths (id, name, utterance, english_name, number) values (7, 'נֶצַח', 'Netzach (Nēṣaḥ)', 'Victory', 7)
insert into paths (id, name, utterance, english_name, number) values (8, 'הוֹד', 'Hod (Hōḏ)', 'Splendour', 8)
insert into paths (id, name, utterance, english_name, number) values (9, 'יְסוֹד', 'Yesod (Yəsōḏ)', 'Foundation', 9)
insert into paths (id, name, utterance, english_name, number) values (10, 'מַלְכוּת', 'Malkuth (Malḵūṯ)', 'Kingdom', 10)
insert into paths (id, name, utterance, english_name, number) values (11, 'א', 'Aleph (ālef)', 'Ox', 11)
insert into paths (id, name, utterance, english_name, number) values (12, 'ב', 'Beth (bēt)', 'House', 12)
insert into paths (id, name, utterance, english_name, number) values (13, 'ג', 'Gimel (gīmel)', 'Camel', 13)
insert into paths (id, name, utterance, english_name, number) values (14, 'ד', 'Daleth (dāleth)', 'Door', 14)
insert into paths (id, name, utterance, english_name, number) values (15, 'ה', 'He (hē)', 'Window', 15)
insert into paths (id, name, utterance, english_name, number) values (16, 'ו', 'Vau (wāw)', 'Nail', 16)
insert into paths (id, name, utterance, english_name, number) values (17, 'ז', 'Zain (zayīn)', 'Sword', 17)
insert into paths (id, name, utterance, english_name, number) values (18, 'ח', 'Cheth (ḥēt)', 'Fence', 18)
insert into paths (id, name, utterance, english_name, number) values (19, 'ט', 'Teth (Ṭēth)', 'Serpent', 19)
insert into paths (id, name, utterance, english_name, number) values (20, 'י', 'Yod (yud)', 'Hand', 20)
insert into paths (id, name, utterance, english_name, number) values (21, 'כ', 'Kaph (kāp̄)', 'Palm', 21)
insert into paths (id, name, utterance, english_name, number) values (22, 'ל', 'Lamed (lāmeḏ)', 'Ox Goad', 22)
insert into paths (id, name, utterance, english_name, number) values (23, 'ם', 'Mem (mēm)', 'Water', 23)
insert into paths (id, name, utterance, english_name, number) values (24, 'נ', 'Nun (nūn)', 'Fish', 24)
insert into paths (id, name, utterance, english_name, number) values (25, 'נ', 'Samekh (sāmeḵ)', 'Prop', 25)
insert into paths (id, name, utterance, english_name, number) values (26, 'ע', 'Ayin (ayin)', 'Eye', 26)
insert into paths (id, name, utterance, english_name, number) values (27, 'פ', 'Peh (pē)', 'Mouth', 27)
insert into paths (id, name, utterance, english_name, number) values (28, 'צ', 'Tzaddi (ṣādī)', 'Fish-hook', 28)
insert into paths (id, name, utterance, english_name, number) values (29, 'ק', 'Qoph (qūp̄)', 'Back of head', 29)
insert into paths (id, name, utterance, english_name, number) values (30, 'ר', 'Resh (rēš)', 'Head', 30)
insert into paths (id, name, utterance, english_name, number) values (31, 'ש', 'Shin (šīn)', 'Tooth', 31)
insert into paths (id, name, utterance, english_name, number) values (32, 'ת', 'Tau (tav)', 'Cross/Mark', 32)